# 5. Find the total revenue generated by each restaurant.

SELECT 
    r.restaurant_id,
    r.name AS restaurant_name,
    COALESCE(SUM(o.total_amount), 0) AS total_revenue
FROM
    restaurants r
        LEFT JOIN
    orders o ON r.restaurant_id = o.restaurant_id
GROUP BY 1 , 2; 

